### ISSUE TITLE
Odio = Hate

### ISSUE THREAD

**Issue by Marl0** [odioapp/odio#53] opened 2019-01-06 16:26 UTC
I just open a new thread on that because the other one is close. May be you can reopen the other one. This is a serious issue and I guaranty you are going to end by changing the name. In Spanish sounds horrible, it is the second lenguage in the world and "odio" is a very wrong word for an radio app

**Comment by Marl0** [comment] 2019-01-06 16:31
I forgot. Great app!!

**Comment by probonopd** [comment] 2019-01-06 19:57
Duplicate of https://github.com/odioapp/odio/issues/37,

**Closed** 2019-01-06 20:11 UTC
Labels: enhancement
