### ISSUE TITLE
[Feature]:why song names do not appear 

### ISSUE THREAD

**Issue by sevketasurgan** [odioapp/odio#93] opened 2019-10-04 11:48 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jo99jo** [comment] 2019-10-20 06:00
I 2nd this request.

**Comment by kekukui** [comment] 2019-11-15 05:22
Duplicate of bug https://github.com/odioapp/odio/issues/16

**Closed** 2020-05-08 06:58 UTC
Labels: enhancement
