### ISSUE TITLE
[For Version 2.0] Backup of Stations

### ISSUE THREAD

**Issue by alexwender1** [odioapp/odio#81] opened 2019-04-09 17:33 UTC
It is important to have a backup mechanism for the saved stations in the library.

To avoid a platform with login and password... It would be interesting to Odio to generate a backup file, which can be restored later (as it currently works with the routers).

**Comment by spiral2k** [comment] 2019-04-09 17:58
Will be in the next version, import a file that export all your settings and favorites stations

**Comment by alexwender1** [comment] 2019-08-13 22:44
@spiral2k Do we have any Beta (or Alpha) versions to test?

**Comment by kekukui** [comment] 2020-03-10 16:07
**note:** This issue is a duplicate of https://github.com/odioapp/odio/issues/41

**Comment by alexwender1** [comment] 2020-05-05 22:20
@spiral2k Is there any information about the release of the new version?

**Comment by spiral2k** [comment] 2020-05-08 05:32
yes, one month for public alpha :)

**Comment by spiral2k** [comment] 2020-05-08 05:32
yes, one month for public beta :)

**Comment by spiral2k** [comment] 2020-05-19 02:04
@alexwender1 @kekukui  by the way, i have updated the readme file with the new 2.0 features

let me know what you think 🤙

**Comment by alexwender1** [comment] 2020-05-19 20:26
> @alexwender1 @kekukui by the way, i have updated the readme file with the new 2.0 features
> 
> let me know what you think call_me_hand

The minimize option for the system tray is essential.

It is interesting to support the control media keys (play/pause, next, previous); the application would be more integrated into the system.

The capture / recording of the streaming is a very positive differential.

See if it is possible to make Odio startup faster. The current version takes about 6s to be available for use (the display of the "History of Radio" can be displayed in the footer, during the transmission of a station).

Evaluate the release of some Beta versions (B1, B2, B3...); so we can send you feedback and review the first translation. If possible, make it available on AppImage.

**Comment by kekukui** [comment] 2020-06-11 03:10
> **let me know what you think**

Looks great, and more than I expected.  For video support you could also pass stream links to an external application like SMplayer or VLC.

**Closed** 2020-07-25 00:45 UTC
Labels: enhancement
